name: Long

on: [push]

jobs:
  task:
    runs-on: ubuntu-latest
    name: Task
    steps:
      - name: Sleep
        uses: actions/setup-node@v1
        run: echo 'Sleeping...'; sleep 60; echo 'Done.';
