name: Test

on: [push]

jobs:
  cancel:
    runs-on: ubuntu-latest
    name: Cancel
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Step
        uses: ./ # Uses an action in the root directory
        with:
          workflow-name: 'continuous-integration.yml'
          access-token: 'ABC123'
